repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      # - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: [--target-version=py38]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
            # default black line length is 88
            # Allow comments up to 150
            --max-line-length=150,
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        entry: bandit
        exclude: ^tests/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        # TODO: Get rid of Any types. mypy doesn't take jsonschema.validate
        # into account
        # args:
        #   - --strict
        additional_dependencies:
          - pandas-stubs
          - types-jsonschema
          - types-PyYAML
        files: ^aws_project_costs

exclude: "^tests/dummy-.*/.*.md$"
